### ISSUE TITLE
Flash, backbutton not working on iOS

### ISSUE THREAD

**Issue by abdullah432** [koiralapankaj7/drishya_picker#9]
**Describe the bug**
1) In camera view, flash and cross icon are not working, in android, it's working fine.
2) Also photo quality is extremely low.

**One suggestion:** If you make it ask for storage permission when the user clicks on the image picker, instead of when the user moves to the page that will be great.

Thanks

Update: Working fine on Tablet. On iPhone 11, after multiple clicks back button works. Flash is not working on iPhone 11.

**Comment by koiralapankaj7** [comment]
Couldn’t reproduce on iPhone6. I don't have access to iPhone 11 as of now so couldn’t say what might be the reason for the flashlight not working. Did you get any exceptions or any information on the console? Regarding number 2. now you can pass your desire resolution. Storage permission behavior can't be altered as of now because images will be fetched as soon as you open the screen. But this can be changed in the future if feel needed.

**Comment by abdullah432** [comment]
https://user-images.githubusercontent.com/48089976/126895926-4c6063c3-a72f-4e52-9182-c9e2a2b220b0.mp4

Here is a screen recording of the issue. 
After multiple clicks, sometimes it works, which means the issue is in `onTap`.

Working fine on Android, iOS Tablets

**Comment by koiralapankaj7** [comment]
WIll check it out.

**Comment by abdullah432** [comment]
It's working on other iPhone devices and only not working on IPhone 6. I think we can ignore it.
